include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    undefined_prefixed_name: ignore
    invalid_annotation_target: ignore
    must_be_immutable: ignore
linter:

